In [4]:
import tensorflow as tf
import numpy as np

In [29]:
z = np.array([[1.,2,3,4],[2,2,3,4],[5,5,5,4]]).T
print(z.T)
y = np.array([[0.,0,1],[0,0,1],[0,0,1],[1,0,0]])
Z = tf.constant(z)
Y = tf.constant(y)
cost = tf.nn.softmax_cross_entropy_with_logits(logits=Z, labels=Y)

D = tf.gradients(cost, Z)
with tf.Session() as s:
    a = np.array(s.run(D)).T.reshape(3,4)
    
print(a)


[[ 1.  2.  3.  4.]
 [ 2.  2.  3.  4.]
 [ 5.  5.  5.  4.]]
[[ 0.01714783  0.0452785   0.10650698 -0.66666667]
 [ 0.04661262  0.0452785   0.10650698  0.33333333]
 [-0.06376045 -0.090557   -0.21301396  0.33333333]]


In [13]:
tf.reset_default_graph()
z = np.array([[1.,-2,3,4],[2,-2,-3,4],[5,-5,5,-4]]).T
Z = tf.constant(z)
A = tf.nn.relu(Z)

with tf.Session() as s:
    a = s.run(A)
    
print(a.shape)
a.T


(4, 3)


array([[ 1.,  0.,  3.,  4.],
       [ 2.,  0.,  0.,  4.],
       [ 5.,  0.,  5.,  0.]])